<?php
//菜单配置文件
return array(
    'index'=>array(
        'name'=>'欢迎界面',
        'icon'=>'icon-home',
        ),
    'settype'=>array(
        'name'=>'配置类别/项管理',
        'icon'=>'icon-list',
        'child'=>array(
            'index'=>array(
                'name'=>'配置类别列表',
                ),
            'modtype'=>array(
                'name'=>'新增/修改配置类别',
                ),
            'android'=>array(
                'name'=>'Android配置项管理',
                ),
            'iphone'=>array(
                'name'=>'Iphone配置项管理',
                ),
            'ipad'=>array(
                'name'=>'Ipad配置项管理',
                ),
            'modsetkey'=>array(
                'name'=>'新增/修改配置项',
                ),
            ),
        ),
    'setval'=>array(
        'name'=>'各端各机型配置',
        'icon'=>'icon-edit',
        'child'=>array(
            'android'=>array(
                'name'=>'Android各机型配置',
                ),
            'iphone'=>array(
                'name'=>'Iphone各机型配置',
                ),
            'ipad'=>array(
                'name'=>'Ipad各机型配置',
                ),
            /*'modsetval'=>array(
                'name'=>'配置修改',
                'hidden'=>1,
                ),*/
            ),
        ),
	'task'=>array(
        'name'=>'任务列表管理',
        'icon'=>'icon-star',
        'child'=>array(
            'index'=>array(
                'name'=>'任务列表管理',
                ),
            'modtask'=>array(
                'name'=>'新增/修改任务',
                ),
			'status'=>array(
                'name'=>'启用/停用任务',
				'hidden'=>1,
                ),
            )
        ),    
    'user'=>array(
        'name'=>'用户信息管理',
        'icon'=>'icon-heart',
        'child'=>array(
            'index'=>array(
                'name'=>'用户管理列表',
                ),
            'disciple'=>array(
                'name'=>'师徒管理列表',
                ),
            'view'=>array(
                'name'=>'查看用户信息',
                'hidden'=>1,
                ),
            )
        ),
    'menu'=>array(
        'name'=>'菜单管理',
        'icon'=>'icon-gift',
        'child'=>array(
            'index'=>array(
                'name'=>'菜单列表管理',
                ),
            'modify'=>array(
                'name'=>'新增/修改菜单',
                )
            )
        ),
	'money'=>array(
        'name'=>'金币零钱管理',
        'icon'=>'icon-usd',
        'child'=>array(
	     'jinbi'=>array(
                'name'=>'金币收入列表',
                ),
	     'lingqian'=>array(
                'name'=>'零钱收入列表',
                ),
            
	     'tixian'=>array(
                'name'=>'零钱提现列表',
				//'hidden'=>1,
                ),
            ),
        ),
        'game'=>array(
            'name'=>'游戏信息管理',
            'icon'=>'icon-gamepad',
            'child'=>array(
                'index'=>array(
                    'name'=>'游戏列表管理',
                    ),
                'modgame'=>array(
                    'name'=>'新增/修改游戏',
                    ),
                'status'=>array(
                    'name'=>'启用/停用任务',
                    'hidden'=>1,
                    ),
                )
        ),
    /*'edit'=>array(
        'name'=>'文案类管理',
        'icon'=>'icon-flag',
        'child'=>array(
			'problem'=>array(
                'name'=>'常见问题管理',
                ),
            ),
        ),*/
    'config'=>array(
        'name'=>'系统总配置',
        'icon'=>'icon-flag',
        /*
        'child'=>array(
            'index'=>array(
                'name'=>'设备查询',
                ),
        ),
        */
    ),
    'statistics'=>array(
        'name'=>'数据统计',
        'icon'=>'icon-signal',
        
        'child'=>array(
            'user'=>array(
                'name'=>'用户统计',
                ),
            'jinbi'=>array(
                'name'=>'金币统计',
                ),
            
            'tixian'=>array(
                'name'=>'提现统计',
                ),
            
        ),
    ),
    'help'=>array(
        'name'=>'帮助中心',
        'icon'=>'icon-comments',
        
        'child'=>array(
            'qa'=>array(
                'name'=>'常见问题',
                ),
            'modqa'=>array(
                'name'=>'新增/修改问题',
                ),
        ),
    ),
    'adminer'=>array(
        'name'=>'管理员管理',
        'icon'=>'icon-user',
        'child'=>array(
            'index'=>array(
                'name'=>'管理员列表',
                ),
            'modify'=>array(
                'name'=>'新增/修改管理员',
                ),
            'right'=>array(
                'name'=>'管理员权限管理',
                'hidden' =>1
                ),
            'mypass'=>array(
                'name'=>'修改密码',
                ),
            ),
        ),
    'record'=>array(
        'name'=>'平台操作记录',
        'icon'=>'icon-file-text',
        ),
	//hicon-tasks  phicon-book  hicon-cog  icon-asterisk icon-book icon-save  icon-hdd icon-fire icon-bolt icon-random
);
